import './globals.css'
import {
  Roboto_Condensed as robotoCondensed,
  Work_Sans as workSans,
} from 'next/font/google'
import { ReactNode } from 'react'
import Header from '@/layout/header'

const roboto = robotoCondensed({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-roboto',
})
const sans = workSans({ subsets: ['latin'], variable: '--font-workSans' })

export const metadata = {
  title: 'Home',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={`${sans.variable} ${roboto.variable} font-primary`}>
        <Header />
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  )
}
