'use client'
import './globals.css'
import {
  Roboto_Condensed as robotoCondensed,
  Work_Sans as workSans,
} from 'next/font/google'
import Link from 'next/link'
import { ReactNode, useState } from 'react'
import { BiPhone, BiHome, BiMenu, BiX } from 'react-icons/bi'
import Image from 'next/image'
import Logo from 'public/logo.png'
import { FaFacebookF, FaInstagram, FaWhatsapp } from 'react-icons/fa'
import { Card } from '@/components/card'

const roboto = robotoCondensed({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-roboto',
})
const sans = workSans({ subsets: ['latin'], variable: '--font-workSans' })

// export const metadata = {
//   title: 'Home',
//   // description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: ReactNode }) {
  const [button, setButton] = useState(false)

  return (
    <html lang="pt-br">
      <body
        className={`${sans.variable} ${roboto.variable} relative font-primary`}
      >
        <header className="absolute right-0 top-0 z-30 h-36 w-screen overflow-x-hidden bg-gradient-to-t from-transparent via-zinc-700 to-zinc-950 md:relative md:h-auto md:w-full md:bg-zinc-950 md:bg-none">
          <section className="relative mx-auto flex w-full items-center justify-between gap-2 pt-2 md:container md:flex-row md:items-center md:gap-5 md:pt-0">
            <div
              className="relative flex w-full items-center justify-between px-6 before:absolute before:left-0 before:h-full before:w-[100vw] before:-translate-x-full
                before:bg-zinc-500 before:content-[none] after:absolute after:right-0 after:h-full after:w-10
                after:translate-x-full after:bg-zinc-500 after:content-[none] after:[clip-path:polygon(0%_0%,100%_50%,0%_100%)] md:order-none
                md:mr-10 md:w-[250px] md:justify-center md:bg-zinc-500 md:p-0 md:before:content-[''] md:after:content-['']
                "
            >
              <Link href="/">
                <Image
                  src={Logo}
                  quality={100}
                  alt="Logo da pagina"
                  className="w-32 md:w-40"
                  priority
                />
              </Link>
              <BiMenu
                className="text-4xl text-light md:hidden"
                onClick={() => {
                  button ? setButton(false) : setButton(true)
                }}
              />
            </div>
            <Card.Root className="hidden md:flex">
              <Card.Icon icon={BiPhone} className="fill-light" />
              <Card.Section>
                <Card.Title text="(13) 9 8839-3565" />
                <Card.Subtitle text="amorimdrywall@gmail.com" />
              </Card.Section>
            </Card.Root>
            <Card.Root className="hidden md:flex">
              <Card.Icon icon={BiHome} className="fill-light" />
              <Card.Section>
                <Card.Title text="Baixada Santista" />
                <Card.Subtitle text="Atendemos toda a região do litoral" />
              </Card.Section>
            </Card.Root>
            <div
              className="absolute bottom-0 right-0 z-10 hidden translate-y-[50%] items-center justify-center gap-8 bg-zinc-500 p-2 before:absolute before:left-[1px]
              before:h-full before:w-10 before:-translate-x-full before:bg-zinc-500 before:[clip-path:polygon(0%_50%,100%_0%,100%_100%)] 
              after:absolute
              after:right-0 after:h-full after:w-[100vw] after:translate-x-full after:bg-zinc-500 md:flex
              "
            >
              <a href="#" target="_blank">
                <FaFacebookF className="fill-light text-2xl text-red-600 hover:fill-base" />
              </a>
              <a
                href="https://www.instagram.com/amorim_drywall/?hl=pt-br"
                target="_blank"
              >
                <FaInstagram className="fill-light text-2xl hover:fill-base" />
              </a>
              <a href="https://wa.me/5513988393565" target="_blank">
                <FaWhatsapp className="fill-light text-3xl hover:fill-base" />
              </a>
            </div>
          </section>
          <nav
            className={`fixed right-0 top-0 z-50 flex h-screen w-screen flex-col justify-evenly bg-black py-6 transition-all md:visible md:static md:z-0 md:h-auto md:w-full md:translate-x-0 md:bg-zinc-200 ${
              button ? 'translate-x-0' : 'translate-x-full'
            } `}
          >
            <ul className="flex h-[50vh] flex-col items-center justify-evenly font-alt text-xl md:container md:mx-auto md:h-auto md:w-2/3 md:flex-row md:justify-evenly">
              <li>
                <Link
                  href="/"
                  className=" uppercase text-light hover:text-light md:text-baseColor lg:text-xl"
                >
                  Home
                </Link>
              </li>
              <li>
                <Link
                  href="manun"
                  className=" uppercase text-light hover:text-light md:text-baseColor lg:text-xl"
                >
                  Serviços
                </Link>
              </li>
              <li>
                <Link
                  href="manun"
                  className=" uppercase text-light hover:text-light md:text-baseColor lg:text-xl"
                >
                  Projetos
                </Link>
              </li>
              <li>
                <Link
                  href="manun"
                  className=" uppercase text-light hover:text-light md:text-baseColor lg:text-xl"
                >
                  Contato
                </Link>
              </li>
              <li className="absolute right-5 top-5 text-5xl text-light hover:text-light md:hidden">
                <BiX
                  onClick={() => {
                    button ? setButton(false) : setButton(true)
                  }}
                />
              </li>
            </ul>
            <div className="flex justify-evenly md:hidden">
              <a href="#" target="_blank">
                <FaFacebookF className="fill-light text-2xl hover:fill-base" />
              </a>
              <a
                href="https://www.instagram.com/amorim_drywall/?hl=pt-br"
                target="_blank"
              >
                <FaInstagram className="fill-light text-2xl hover:fill-base" />
              </a>
              <a href="https://wa.me/5513988393565" target="_blank">
                <FaWhatsapp className="fill-light text-3xl hover:fill-base" />
              </a>
            </div>
          </nav>
        </header>
        <main>{children}</main>
        <footer className="relative overflow-x-hidden bg-[url('/footer-bg.jpg')] bg-cover bg-top after:absolute after:inset-0 after:bg-zinc-950 after:opacity-90">
          <section className="relative z-20 space-y-5 p-5 md:container md:mx-auto md:grid md:grid-cols-3 md:items-center md:gap-x-20 md:p-0 md:px-10 md:py-8 lg:grid-cols-7 lg:gap-16 lg:space-y-0 lg:px-0">
            <div className="col-span-3 text-center lg:col-span-2 lg:col-start-2">
              <Link href="/">
                <Image
                  src={Logo}
                  quality={100}
                  alt="Logo da pagina"
                  className="mx-auto w-32"
                  priority
                />
              </Link>
              <p className="text-xs text-light md:text-sm">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Numquam ipsa quam maiores quaerat ea odit id perspiciatis, qui
                omnis quisquam dolores!
              </p>
            </div>
            <div className="col-span-2 space-y-3">
              <div>
                <h2 className="font-alt text-xl text-white">Páginas</h2>
                <hr className="border-light" />
              </div>
              <ul className="grid grid-cols-2">
                <li>
                  <Link
                    href="/"
                    className="text-sm capitalize text-light hover:text-baseColor"
                  >
                    Home
                  </Link>
                </li>
                <li>
                  <Link
                    className="text-sm capitalize text-light hover:text-baseColor"
                    href="manun"
                  >
                    Serviços
                  </Link>
                </li>
                <li>
                  <Link
                    className="text-sm capitalize text-light hover:text-baseColor"
                    href="manun"
                  >
                    Projetos
                  </Link>
                </li>
                <li>
                  <Link
                    className="text-sm capitalize text-light hover:text-baseColor"
                    href="manun"
                  >
                    Contato
                  </Link>
                </li>
                <li>
                  <Link
                    className="text-sm capitalize text-light hover:text-baseColor"
                    href="policy"
                  >
                    Privacidade e termos
                  </Link>
                </li>
              </ul>
            </div>
            <div className="space-y-3">
              <div>
                <h2 className="font-alt text-xl text-white">Contato</h2>
                <hr className="border-light" />
              </div>
              <ul className="flex flex-col items-center justify-center sm:items-start">
                <li>
                  <Link
                    href="https://wa.me/5513988393565"
                    target="_blank"
                    className="text-sm text-light hover:text-baseColor"
                  >
                    {'(13) 9 8839-3565'}
                  </Link>
                </li>
                <li>
                  <Link
                    className="text-sm text-light hover:text-baseColor"
                    href="https://www.instagram.com/amorim_drywall/?hl=pt-br"
                    target="_blank"
                  >
                    @AmorimDrywall
                  </Link>
                </li>
                <li>
                  <Link
                    className="text-sm text-light hover:text-baseColor"
                    href="#"
                  >
                    amorimdrywall@gmail.com
                  </Link>
                </li>
              </ul>
            </div>
            <div
              className="static flex items-center justify-center gap-6 rounded bg-zinc-500 p-2 before:absolute before:left-0 before:h-full before:w-[100vw] before:-translate-x-full before:bg-zinc-500
              before:content-[none] after:absolute after:right-0 after:h-full after:w-10 after:translate-x-full after:bg-zinc-500 after:content-[none]
              after:[clip-path:polygon(0%_0%,100%_50%,0%_100%)] md:absolute md:bottom-0 md:left-0 md:z-10 md:translate-x-0
              md:translate-y-[50%] md:gap-8 md:rounded-none md:before:content-[''] md:after:content-['']
              "
            >
              <a href="#" target="_blank">
                <FaFacebookF className="fill-light text-red-600 hover:fill-base md:text-2xl" />
              </a>
              <a
                href="https://www.instagram.com/amorim_drywall/?hl=pt-br"
                target="_blank"
              >
                <FaInstagram className="fill-light hover:fill-base md:text-2xl" />
              </a>
              <a href="https://wa.me/5513988393565" target="_blank">
                <FaWhatsapp className="fill-light hover:fill-base md:text-2xl" />
              </a>
            </div>
          </section>
          <section className="relative z-10 flex flex-col items-center justify-center gap-2 border-t-[1px] border-light p-5 text-center text-sm text-light md:container md:mx-auto">
            <p className="">
              AmorimDrywall &copy; 2023 Todos os direitos reservados
            </p>
            <p>
              Desenvolvido por{' '}
              <a
                href="https://github.com/MoreiraAlex"
                target="_blank"
                className="hover:text-baseColor"
              >
                Alex Moreira
              </a>
            </p>
          </section>
        </footer>
      </body>
    </html>
  )
}
