# Generated by Django 4.1.1 on 2022-09-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(default='', upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='job',
            name='img',
            field=models.ImageField(default='', upload_to='static/media'),
        ),
    ]
