# Generated by Django 4.1.1 on 2022-09-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('tags', models.TextField(default='')),
                ('date', models.DateField(default='')),
                ('img', models.ImageField(default='', upload_to='static/media/upload/thumbnail')),
            ],
            options={
                'verbose_name': 'Trabalho',
                'verbose_name_plural': 'Trabalhos',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('img', models.ImageField(default='', upload_to='static/media/upload/photos')),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galeria',
            },
        ),
    ]
